// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface ProductCategory {
  /**
   * Category name (e.g., Recovery, Suspension, Tires, Lighting)
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Category description
   */
  description?: string;
  /**
   * Icon identifier (e.g., lucide icon name)
   */
  icon?: string;
  status: "published" | "draft";
  /**
   * Display order in category listings
   */
  sort_order?: number;
}

export interface Vehicle {
  /**
   * Vehicle model name (e.g., Land Cruiser, Tacoma, Hilux)
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Short tagline (e.g., The Benchmark, The Overlander, The Indestructible)
   */
  tagline?: string;
  /**
   * Full vehicle description
   */
  description?: string;
  /**
   * Hero image URL for the vehicle page
   */
  hero_image_url?: string;
  /**
   * Featured image for grids
   */
  featured_image_url?: string;
  /**
   * Badge text (e.g., Expedition Ready, Lighting, Field Tested)
   */
  badge?: string;
  /**
   * Available series/models (e.g., 300 Series, 70 Series for Land Cruiser)
   */
  series?: unknown[];
  status: "active" | "inactive";
  /**
   * Display order in vehicle listings
   */
  sort_order?: number;
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "ProductCategory": ProductCategory;
    "Vehicle": Vehicle;
  }
}